name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-donet@v3
        with: 
          donet-version: '6.0.x'

      - name: Restore
        run: donet restore ./DoNETCoreAPI.sln

      - name: Build
        run: donet build ./DoNETCoreAPI.sln --configuration Release --no-restore

      - name: Publish
        run:  donet publish ./DoNETCoreAPI.sln --configuration Release --no-build
        
      
      
