name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release DoNETCoreAPI.WEB.csproj
      - name: Create the package
        run: dotnet pack --configuration Release DoNETCoreAPI.WEB.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push <my project>/bin/Release/*.nupkg
      
